### ISSUE TITLE
Will not work with .jpg

### ISSUE THREAD

**Issue by PioKozi** [PioKozi/XOREncrypt#1]
Will work with txt and probably most source code, but jpg won't work. Starting bytes are wrong.

**Comment by Bronek** [comment]
Use `o []byte`, e.g.

```
		var o []byte
		for i, arg := range f {
			o = append(o, byte(byte(arg) ^ byte(key[i % len(key)])))
		}
```

Also, no need to extend `key`, just use mod as demonstrated above.

**Comment by Bronek** [comment]
For better performance, pre-allocate `o` to the required `len(f)` instead of appending each byte.
